CREATE DATABASE eu_crime;

USE eu_crime;

CREATE TABLE crime_1998_2007 (
	DATAFLOW VARCHAR(20),
    LAST_UPDATE DATETIME, 
    freq CHAR(6), 
    unit CHAR(6), 
    iccs VARCHAR(250), 
    geo VARCHAR(50),
    TIME_PERIOD YEAR, 
    OBS_VALUE SMALLINT UNSIGNED, 
    OBS_FLAG VARCHAR(50) DEFAULT NULL,
    CONF_STATUS VARCHAR(50) DEFAULT NULL
);

ALTER TABLE crime_1998_2007
MODIFY COLUMN OBS_VALUE INT UNSIGNED;

SELECT @@secure_file_priv;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Recorded Crimes 1998-2007.csv'
INTO TABLE crime_1998_2007
FIELDS TERMINATED BY ','
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * 
FROM
	crime_1998_2007;